### ISSUE TITLE
Crash on Windows 7/10 - Nuke 11.1

### ISSUE THREAD

**Issue by bazarus** [buddly27/smaa-nuke#1]
@buddly27, Thank you for great plugin.
I kinda successfully compiled plugin, but get instant crash after trying to connect viewer to this node with connected image.  Both on CPU and GPU. Can you tell me please how can i solve this?

CPU:
`0x000000000AC31978 (0x000000C300000000 0x0000080000000000 0x0000061300000800 0x0
000080000000001), SMAALumaEdges3() + 0x718 bytes(s)
0x00001F8000000000 (0x0000080000000000 0x0000061300000800 0x0000080000000001 0x0
030A00000000614) <unknown module>
0x000000C300000000 (0x0000061300000800 0x0000080000000001 0x0030A00000000614 0x0
00000006CDE8000) <unknown module>
0x0000080000000000 (0x0000080000000001 0x0030A00000000614 0x000000006CDE8000 0x0
000000077911961) <unknown module>
0x0000061300000800 (0x0030A00000000614 0x000000006CDE8000 0x0000000077911961 0x0
000000000000000) <unknown module>
0x0000080000000001 (0x000000006CDE8000 0x0000000077911961 0x0000000000000000 0x0
00000006CDEA000) <unknown module>
0x0030A00000000614 (0x0000000077911961 0x0000000000000000 0x000000006CDEA000 0x0
000000000000000) <unknown module>`

GPU:
`0x000007FEFD9FA06D (0x0000000006BCCC20 0x000000005A502240 0xFFFFFFFF00000001 0x0
00007FEE6020108), RaiseException() + 0x3D bytes(s)
0x000007FEFAFB4462 (0x000007FEE6020000 0x0000000006BCCC20 0x0000000006BCCFA0 0x0
000000006BCCFA0), _CxxThrowException() + 0xC2 bytes(s)
0x000007FEE6021F4F (0x000000005A502630 0x0000000006BCC8A0 0x0000000006D5DF90 0x0
000000000000007)
0x000007FEE6024458 (0x0000000000000000 0x000000000344F860 0x000000000344F860 0x0
00000000344F860)
0x000007FEEF0BE00D (0x000000001B818D70 0x000000005A507C80 0x000000000344E780 0x0
00000005A507C80), ?renderStripe@PlanarIop@Image@DD@@MEAA?AVImagePlane@23@_KAEBVC
hannelSet@23@@Z() + 0x14D bytes(s)
0x000007FEEF0BD52A (0x0000000000000048 0x000007FEEF086A80 0x000007FEEF07BF60 0x0
000000000000000), ?engine@PlanarIop@Image@DD@@MEAAXHHHAEBVChannelSet@23@AEAVRow@
23@@Z() + 0x1FA bytes(s)
0x000007FEEEF9A288 (0x000000000344F680 0x0000000000000800 0x000000005A507C80 0x0
00000000344F680), ?_copyState@Iop@Image@DD@@QEAAXPEAV123@@Z() + 0x3768 bytes(s)
0x000007FEEF035477 (0x000000003EAD9E20 0x000007FEEF071A27 0x000000003D0EDFA0 0x0
00007FEEF086A8E), ?get@Iop@Image@DD@@UEAAXHHHAEBVChannelSet@23@AEAVRow@23@@Z() +
 0x3E7 bytes(s)
0x000007FEEF066AED (0x000000003EAD9FA0 0x000000000344E780 0x0000000000000800 0x0
000000000000060), ?engine@NukeWrapper@Image@DD@@UEAAXHHHAEBVChannelSet@23@AEAVRo
w@23@@Z() + 0x6D bytes(s)
0x000007FEEEF9A288 (0x000000000344E780 0x000000005A506CC8 0x000000005A506CB0 0x0
00000005A506CC8), ?_copyState@Iop@Image@DD@@QEAAXPEAV123@@Z() + 0x3768 bytes(s)
0x000007FEEEF99843 (0x000000005A506CB0 0x0000000000000000 0x0000000000000000 0x0
000000006CB77A0), ?_copyState@Iop@Image@DD@@QEAAXPEAV123@@Z() + 0x2D23 bytes(s)
0x000007FEEEF99523 (0x0000000000000800 0x000000005A506D30 0x000000005A507C80 0x0
000000000000000), ?_copyState@Iop@Image@DD@@QEAAXPEAV123@@Z() + 0x2A03 bytes(s)
0x000007FEEF035502 (0x000000003F9D06B0 0x0000000003470000 0x0000000003470000 0x0
00000005A507C80), ?get@Iop@Image@DD@@UEAAXHHHAEBVChannelSet@23@AEAVRow@23@@Z() +
 0x472 bytes(s)
0x000007FEEF0BBA7E (0x000000003F994790 0x0000000003470000 0x0000000000000800 0x0
000000000000000), ?engine@PixelIop@Image@DD@@MEAAXHHHAEBVChannelSet@23@AEAVRow@2
3@@Z() + 0xEE bytes(s)
0x000007FEEEF9A288 (0x0000000003470000 0x0000000000000800 0x000000005A507C80 0x0
000000000000000), ?_copyState@Iop@Image@DD@@QEAAXPEAV123@@Z() + 0x3768 bytes(s)
0x000007FEEF035477 (0x000000003F7C6EA0 0x000000000344EA00 0x000000000344EA00 0x0
00000005A507C80), ?get@Iop@Image@DD@@UEAAXHHHAEBVChannelSet@23@AEAVRow@23@@Z() +
 0x3E7 bytes(s)
0x000007FEEF0BBA7E (0x000000003EF323F0 0x000000000344EA00 0x0000000000000800 0x0
000000000000000), ?engine@PixelIop@Image@DD@@MEAAXHHHAEBVChannelSet@23@AEAVRow@2
3@@Z() + 0xEE bytes(s)
0x000007FEEEF9A288 (0x000000000344EA00 0x0000000000000800 0x000000005A507C80 0x0
000000000000000), ?_copyState@Iop@Image@DD@@QEAAXPEAV123@@Z() + 0x3768 bytes(s)
0x000007FEEF035477 (0x000000003F9D09D0 0x00000000034703C0 0x00000000034703C0 0x0
00000005A507C80), ?get@Iop@Image@DD@@UEAAXHHHAEBVChannelSet@23@AEAVRow@23@@Z() +
 0x3E7 bytes(s)
0x000007FEEF0BBA7E (0x000000003F9946D0 0x00000000034703C0 0x0000000000000800 0x0
000000000000000), ?engine@PixelIop@Image@DD@@MEAAXHHHAEBVChannelSet@23@AEAVRow@2
3@@Z() + 0xEE bytes(s)
0x000007FEEEF9A288 (0x00000000034703C0 0x0000000000000800 0x000000005A507C80 0x0
000000000000000), ?_copyState@Iop@Image@DD@@QEAAXPEAV123@@Z() + 0x3768 bytes(s)
0x000007FEEF035477 (0x000000003F9D0F20 0x000000000347B440 0x000000000347B440 0x0
00000005A507C80), ?get@Iop@Image@DD@@UEAAXHHHAEBVChannelSet@23@AEAVRow@23@@Z() +
 0x3E7 bytes(s)
0x000007FEEF0BBA7E (0x000000003F994B50 0x000000000347B440 0x0000000000000800 0x0
000000000000000), ?engine@PixelIop@Image@DD@@MEAAXHHHAEBVChannelSet@23@AEAVRow@2
3@@Z() + 0xEE bytes(s)
0x000007FEEEF9A288 (0x000000000347B440 0x0000000000000800 0x000000005A507C80 0x0
000000000000000), ?_copyState@Iop@Image@DD@@QEAAXPEAV123@@Z() + 0x3768 bytes(s)
0x000007FEEF035477 (0x000000003F9D11F0 0x0000000003470960 0x0000000003470960 0x0
00000005A507C80), ?get@Iop@Image@DD@@UEAAXHHHAEBVChannelSet@23@AEAVRow@23@@Z() +
 0x3E7 bytes(s)
0x000007FEEF0BBA7E (0x000000003F994E50 0x0000000003470960 0x0000000000000800 0x0
000000000000000), ?engine@PixelIop@Image@DD@@MEAAXHHHAEBVChannelSet@23@AEAVRow@2
3@@Z() + 0xEE bytes(s)
0x000007FEEEF9A288 (0x0000000003470960 0x0000000000000800 0x000000005A507C80 0x0
00000005A507990), ?_copyState@Iop@Image@DD@@QEAAXPEAV123@@Z() + 0x3768 bytes(s)
0x000007FEEF035477 (0x000000005A507C80 0x0000000006A52C90 0x0000000000000000 0x0
000000006A52C90), ?get@Iop@Image@DD@@UEAAXHHHAEBVChannelSet@23@AEAVRow@23@@Z() +
 0x3E7 bytes(s)
0x000007FEE369BEFE (0x0000000000000000 0x0000000006A52C90 0x0000000000000000 0x0
00007FEEF102A00), ?gpuEngine_GL_end_recursive@ReduceGPUOps@Nuke@@AEAAXPEAVGPUCon
text@Image@DD@@PEAVIop@45@@Z() + 0x31AE bytes(s)
0x000007FEE2EF2531 (0x0000000006A52C90 0x00000000FFFFFFF0 0x0000000000000000 0x0
000000000000E54), ?StartAnalytics@Analytics@Nuke@@YAXXZ() + 0x1CF1 bytes(s)
0x000007FEEF102A9D (0x0000000006B23960 0x0000000006A52C90 0x0000000000000000 0x0
000000006B23960), ?setThreadGUIMode@Image@DD@@YAX_N@Z() + 0xCD bytes(s)
0x000007FEF1CCBEED (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0
000000000000000), _crt_at_quick_exit() + 0x7D bytes(s)
0x00000000779059CD (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0
000000000000000), BaseThreadInitThunk() + 0xD bytes(s)
0x0000000077B3A561 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0
000000000000000), RtlUserThreadStart() + 0x21 bytes(s)`

**Comment by buddly27** [comment]
@bazarus I noticed the same behavior on CentOS. This was due to a mishandling of channels output in the blink scripts and an incorrect image creation from SMAA textures.
Could you give it another try and let me know if that solved it for you?
